### ISSUE TITLE
Ruta Diana F

### ISSUE THREAD

**Issue by JidokaCommunity** [JidokaCommunity/trainning#2]

**Comment by JidokaCommunity** [comment]
**Plan de formación**
- [x] [ Curso Lógica de Programación ](https://www.udemy.com/course/aprende-logica-de-programacion/learn/lecture/27553458?start=0#overview)
- [x] [Curso Lógica de Programación Avanzada](https://www.udemy.com/course/aprende-logica-de-programacion-avanzado/learn/lecture/29294378?start=0#overview)     
- [ ] [Curso Java Profesional desde cero](https://drive.google.com/drive/folders/1GWbZ6AS2D4tJCPkNerxlA31VpSo0b33E?usp=sharing)       
- [ ] [ Curso API- Rest](https://drive.google.com/drive/folders/137RzGjBm1VeUkMPXpIpA3K1ZMnt6EvJY)      
- [x] [ Git - Githup]( https://platzi.com/cursos/git-github/)     
- [ ] [Curso de Docker](https://drive.google.com/drive/folders/1irQ22NuKdO3xiJeO3THIdkqrYxlKV0D0)       
- [x] [Curso SQL]( https://www.udemy.com/course/aprende-sql-desde-cero-hasta-avanzado-como-un-profesional/)

      
**Retos Java Hackerank**

- [x] [Sustring]( https://www.hackerrank.com/challenges/java-substring/problem?isFullScreen=true)
- [x] [String Reverse](https://www.hackerrank.com/challenges/java-string-reverse/problem?isFullScreen=true)
- [x] [If-else](https://www.hackerrank.com/challenges/java-if-else/problem?isFullScreen=true)
- [x] [Loops](https://www.hackerrank.com/challenges/java-loops-i/problem?isFullScreen=true)
- [x] [Into String](https://www.hackerrank.com/challenges/java-int-to-string/problem?isFullScreen=true)
- [x] [Intanceof](https://www.hackerrank.com/challenges/java-instanceof-keyword/problem?isFullScreen=true)
- [x] [InHeritance](https://www.hackerrank.com/challenges/java-inheritance-1)
- [x] [Method Overriding](https://www.hackerrank.com/challenges/java-method-overriding)
- [x] [Birhday Cake Candels](https://www.hackerrank.com/challenges/birthday-cake-candles/problem?isFullScreen=true)
- [x] [Value Palindrome](https://www.hackerrank.com/challenges/richie-rich/problem?isFullScreen=true)
- [x] [Pairs](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [ ] [Fibonacci](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [ ] [Fibonacci Numbers](https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem?h_r=internal-search)

**Retos SQL**

- [x] [Select all](https://www.hackerrank.com/challenges/select-all-sql/problem?isFullScreen=true)
- [x] [Japanese Cities'Name](https://www.hackerrank.com/challenges/japanese-cities-name/problem?isFullScreen=true)
- [x] [New Companies](https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true)
- [ ] [Weather Observation station 20](https://www.hackerrank.com/challenges/weather-observation-station-20/problem?isFullScreen=true)
- [ ] [The report](https://www.hackerrank.com/challenges/the-report/problem?isFullScreen=true)

**Taller de Springboot**-  taller para construir microservicios desde cero, estos tres enlaces son una guía para construir microservicios en Springboot, se deben leer y desarrollar en el mismo orden que se citan a continuación:

- [ ] [Parte 1](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-1/)
- [ ] [Parte 2](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-2/)
- [ ] [Parte 3](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-3/)

**Certificación Scrum Foundation** 

- [x] Certificado Scrum

**Comment by Diflorezd** [comment]
![HackerRank If-Else](https://github.com/JidokaCommunity/trainning/assets/170475369/fb479cc5-ab72-4d07-ab7c-68abec0eac8f)

Adjunto evidencia de reto de HackerRank correspondiente al manejo de condicionales lógicos If-Else.

**Comment by Diflorezd** [comment]
![Image](https://github.com/JidokaCommunity/trainning/assets/170475369/b02cd02e-ba1c-48bb-84b2-efa6a8c942dd)

Adjunto evidencia de aprobación reto correspondiente a bucles.

**Comment by JidokaCommunity** [comment]
Esta semana continua con los retos de hackerank

**Comment by JidokaCommunity** [comment]
pendiente de retos

**Comment by Diflorezd** [comment]
![HackerRank Sustring](https://github.com/JidokaCommunity/trainning/assets/170475369/bedcd637-3c18-429c-90fb-876e163ea4cb)

Adjunto evidencia reto correspondiente a Sustring

**Comment by Diflorezd** [comment]
![HackerRank IntoString](https://github.com/JidokaCommunity/trainning/assets/170475369/5b86cb79-7f66-408b-a47b-2b0b9b7edb37)

Adjunto Evidencia reto correspondiente a IntoString

**Comment by Diflorezd** [comment]
![Hacker Rank String Reverse](https://github.com/JidokaCommunity/trainning/assets/170475369/5f097524-71dd-4e41-b7a8-12313e0388ee)

Adjunto evidencia reto correspondiente a String Reverse.

**Comment by Diflorezd** [comment]
Adjunto evidencia de finalización de curso de SQL. 

![image](https://github.com/user-attachments/assets/85ed0e43-c278-4950-823f-7d550547b7c1)

**Comment by Diflorezd** [comment]
Adjunto evidencia de Reto SQL - Select All
![HackerRank Retos SQL Select All](https://github.com/user-attachments/assets/f6bc3637-307d-4c63-b7f9-e9fefbad107b)

**Comment by Diflorezd** [comment]
Adjunto evidencia Reto SQL Japanese Cities Names

![HackerRank Retos SQL Japanese Cities Names](https://github.com/user-attachments/assets/f4434a67-bb2c-4b5a-940e-5a1cae6d5ee4)

**Comment by Diflorezd** [comment]
Adjunto evidencia Reto SQL New Companies
![HackerRank Retos SQL New Companies](https://github.com/user-attachments/assets/855c98c9-47cf-41b7-8b1f-eb7f7cb365d2)
