### ISSUE TITLE
Ruta Samuel

### ISSUE THREAD

**Issue by JidokaCommunity** [JidokaCommunity/trainning#3]
**Plan de formación**
- [x] [ Curso Lógica de Programación ](https://www.udemy.com/course/aprende-logica-de-programacion/learn/lecture/27553458?start=0#overview)
- [x] [Curso Lógica de Programación Avanzada](https://www.udemy.com/course/aprende-logica-de-programacion-avanzado/learn/lecture/29294378?start=0#overview)     
- [x] [Curso Java Profesional desde cero](https://drive.google.com/drive/folders/1GWbZ6AS2D4tJCPkNerxlA31VpSo0b33E?usp=sharing)       
- [x] [ Curso API- Rest](https://drive.google.com/drive/folders/137RzGjBm1VeUkMPXpIpA3K1ZMnt6EvJY)      
- [x] [ Git - Githup]( https://platzi.com/cursos/git-github/)     
- [x] [Curso de Docker](https://drive.google.com/drive/folders/1irQ22NuKdO3xiJeO3THIdkqrYxlKV0D0)       
- [x] [Curso SQL]( https://www.udemy.com/course/aprende-sql-desde-cero-hasta-avanzado-como-un-profesional/)

      
**Retos Java Hackerank**

- [x] [Sustring]( https://www.hackerrank.com/challenges/java-substring/problem?isFullScreen=true)
- [x] [String Reverse](https://www.hackerrank.com/challenges/java-string-reverse/problem?isFullScreen=true)
- [x] [If-else](https://www.hackerrank.com/challenges/java-if-else/problem?isFullScreen=true)
- [x] [Loops](https://www.hackerrank.com/challenges/java-loops-i/problem?isFullScreen=true)
- [x] [Into String](https://www.hackerrank.com/challenges/java-int-to-string/problem?isFullScreen=true)
- [x] [Intanceof](https://www.hackerrank.com/challenges/java-instanceof-keyword/problem?isFullScreen=true)
- [x] [InHeritance](https://www.hackerrank.com/challenges/java-inheritance-1)
- [x] [Method Overriding](https://www.hackerrank.com/challenges/java-method-overriding)
- [x] [Birhday Cake Candels](https://www.hackerrank.com/challenges/birthday-cake-candles/problem?isFullScreen=true)
- [x] [Value Palindrome](https://www.hackerrank.com/challenges/richie-rich/problem?isFullScreen=true)
- [x] [Pairs](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [x] [Fibonacci](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [x] [Fibonacci Numbers](https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem?h_r=internal-search)

**Retos SQL**

- [x] [Select all](https://www.hackerrank.com/challenges/select-all-sql/problem?isFullScreen=true)
- [x] [Japanese Cities'Name](https://www.hackerrank.com/challenges/japanese-cities-name/problem?isFullScreen=true)
- [x] [New Companies](https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true)
- [x] [Weather Observation station 20](https://www.hackerrank.com/challenges/weather-observation-station-20/problem?isFullScreen=true)
- [x] [The report](https://www.hackerrank.com/challenges/the-report/problem?isFullScreen=true)

**Taller de Springboot**-  taller para construir microservicios desde cero, estos tres enlaces son una guía para construir microservicios en Springboot, se deben leer y desarrollar en el mismo orden que se citan a continuación:

- [x] [Parte 1](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-1/)
- [x] [Parte 2](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-2/)
- [x] [Parte 3](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-3/)

**Certificación Scrum Foundation** 

- [x] Certificado Scrum

**Comment by JidokaCommunity** [comment]
Esta en la optimización de docker

**Comment by JidokaCommunity** [comment]
pendiente para la prox semana presentar el examen de scrum

**Comment by CardonaSam1997** [comment]
![SubString](https://github.com/JidokaCommunity/trainning/assets/121903742/69530ae6-5d9a-423e-806a-27c12f639468)

**Comment by CardonaSam1997** [comment]
![StringReverse](https://github.com/JidokaCommunity/trainning/assets/121903742/5106eacc-7c77-481a-83ca-5b6fec158127)

**Comment by CardonaSam1997** [comment]
![if-else](https://github.com/JidokaCommunity/trainning/assets/121903742/ccaeabe1-b293-4770-a4ee-b158b4834be5)

**Comment by CardonaSam1997** [comment]
![Loops](https://github.com/JidokaCommunity/trainning/assets/121903742/28ddeca9-ba92-4541-99b9-9ad514ddfb0c)

**Comment by CardonaSam1997** [comment]
![stringValueOf](https://github.com/JidokaCommunity/trainning/assets/121903742/c3f05260-ce86-4b40-8529-dc070fffda53)

**Comment by CardonaSam1997** [comment]
![instanceOf](https://github.com/JidokaCommunity/trainning/assets/121903742/1089c7dd-08bb-4460-abb0-bb34e248a273)

**Comment by CardonaSam1997** [comment]
![herencia](https://github.com/JidokaCommunity/trainning/assets/121903742/7bbc6d83-71b9-42c2-8517-b0e71a14c4f6)

**Comment by CardonaSam1997** [comment]
![sobreescribir](https://github.com/JidokaCommunity/trainning/assets/121903742/6a567916-65b8-4ad0-8e8c-b4bf6068e367)

**Comment by CardonaSam1997** [comment]
![birthday cake](https://github.com/JidokaCommunity/trainning/assets/121903742/a0ec5e59-489e-486f-9fb0-e3383ec5a666)

**Comment by CardonaSam1997** [comment]
![Pairs](https://github.com/JidokaCommunity/trainning/assets/121903742/e756db23-54bb-4be6-8648-aae0adc8243d)

**Comment by CardonaSam1997** [comment]
![palindrome](https://github.com/JidokaCommunity/trainning/assets/121903742/ad6b5e4e-79f4-4d16-82de-ab36877dae90)

**Comment by CardonaSam1997** [comment]
![fibonacci-Recursivo](https://github.com/JidokaCommunity/trainning/assets/121903742/42f26995-3cf1-4bda-9f5a-c40f199af755)

**Comment by CardonaSam1997** [comment]
![Select All](https://github.com/JidokaCommunity/trainning/assets/121903742/6d17ad1b-73d0-4fa7-9eb8-d49a7bb97b91)

**Comment by CardonaSam1997** [comment]
![WhereConuntryCode](https://github.com/JidokaCommunity/trainning/assets/121903742/9cdd4580-cab8-4cc7-a31a-68de917cc781)

**Comment by CardonaSam1997** [comment]
![new-companies](https://github.com/JidokaCommunity/trainning/assets/121903742/b0fe25f7-db9d-426a-a59c-b7278016e669)

**Comment by CardonaSam1997** [comment]
![sql-station](https://github.com/JidokaCommunity/trainning/assets/121903742/1d647c08-a063-4f95-ba65-8803615aa1d3)

**Comment by CardonaSam1997** [comment]
![Microservice-1](https://github.com/JidokaCommunity/trainning/assets/121903742/5f3b6209-486d-4b6c-8fcd-9b774892c793)

**Comment by CardonaSam1997** [comment]
![Microservice-2](https://github.com/JidokaCommunity/trainning/assets/121903742/0aca6918-b8f6-4252-a457-11fd1e847445)

**Comment by CardonaSam1997** [comment]
![msvc-3](https://github.com/JidokaCommunity/trainning/assets/121903742/25da3ce4-1ac9-466a-a16b-98bfa2f75d99)

**Comment by CardonaSam1997** [comment]
![report](https://github.com/JidokaCommunity/trainning/assets/121903742/a8b9ea0f-ff8f-4ece-a68c-25b42dea741f)

**Comment by CardonaSam1997** [comment]
![image](https://github.com/user-attachments/assets/a2f15465-8486-46c2-be2a-83aa75654286)

**Comment by JidokaCommunity** [comment]
terminando el curso docker

**Comment by JidokaCommunity** [comment]
Continua en el curso de Docker
