### ISSUE TITLE
Ruta Leidy

### ISSUE THREAD

**Issue by JidokaCommunity** [JidokaCommunity/trainning#7]
**Plan de formación**
- [ ] [ Curso Lógica de Programación ](https://www.udemy.com/course/aprende-logica-de-programacion/learn/lecture/27553458?start=0#overview)
- [ ] [Curso Lógica de Programación Avanzada](https://www.udemy.com/course/aprende-logica-de-programacion-avanzado/learn/lecture/29294378?start=0#overview)     
- [x] [Curso Java Profesional desde cero](https://drive.google.com/drive/folders/1GWbZ6AS2D4tJCPkNerxlA31VpSo0b33E?usp=sharing)       
- [x] [ Curso API- Rest](https://drive.google.com/drive/folders/137RzGjBm1VeUkMPXpIpA3K1ZMnt6EvJY)      
- [x] [ Git - Githup]( https://platzi.com/cursos/git-github/)     
- [ ] [Curso de Docker](https://drive.google.com/drive/folders/1irQ22NuKdO3xiJeO3THIdkqrYxlKV0D0)       
- [x] [Curso SQL]( https://www.udemy.com/course/aprende-sql-desde-cero-hasta-avanzado-como-un-profesional/)

      
**Retos Java Hackerank**

- [x] [Sustring]( https://www.hackerrank.com/challenges/java-substring/problem?isFullScreen=true)
- [x] [String Reverse](https://www.hackerrank.com/challenges/java-string-reverse/problem?isFullScreen=true)
- [x] [If-else](https://www.hackerrank.com/challenges/java-if-else/problem?isFullScreen=true)
- [x] [Loops](https://www.hackerrank.com/challenges/java-loops-i/problem?isFullScreen=true)
- [x] [Into String](https://www.hackerrank.com/challenges/java-int-to-string/problem?isFullScreen=true)
- [x] [Intanceof](https://www.hackerrank.com/challenges/java-instanceof-keyword/problem?isFullScreen=true)
- [x] [InHeritance](https://www.hackerrank.com/challenges/java-inheritance-1)
- [x] [Method Overriding](https://www.hackerrank.com/challenges/java-method-overriding)
- [x] [Birhday Cake Candels](https://www.hackerrank.com/challenges/birthday-cake-candles/problem?isFullScreen=true)
- [x] [Value Palindrome](https://www.hackerrank.com/challenges/richie-rich/problem?isFullScreen=true)
- [x] [Pairs](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [x] [Fibonacci](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [x] [Fibonacci Numbers](https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem?h_r=internal-search)

**Retos SQL**

- [x] [Select all](https://www.hackerrank.com/challenges/select-all-sql/problem?isFullScreen=true)
- [x] [Japanese Cities'Name](https://www.hackerrank.com/challenges/japanese-cities-name/problem?isFullScreen=true)
- [x] [New Companies](https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true)
- [x] [Weather Observation station 20](https://www.hackerrank.com/challenges/weather-observation-station-20/problem?isFullScreen=true)
- [x] [The report](https://www.hackerrank.com/challenges/the-report/problem?isFullScreen=true)

**Taller de Springboot**-  taller para construir microservicios desde cero, estos tres enlaces son una guía para construir microservicios en Springboot, se deben leer y desarrollar en el mismo orden que se citan a continuación:

- [x] [Parte 1](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-1/)
- [x] [Parte 2](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-2/)
- [x] [Parte 3](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-3/)

**Certificación Scrum Foundation** 

- [x] Certificado Scrum

**Comment by JidokaCommunity** [comment]
Avanza a la sección 12 de Docker para avanzar con dos secciones

**Comment by Arizat** [comment]
Se realiza ejercicio "Substring" correctamente. 
<img width="953" alt="substring" src="https://github.com/JidokaCommunity/trainning/assets/131737056/93ec851b-06bb-4c04-ba79-981ecac10094">

**Comment by Arizat** [comment]
Se realiza el ejercicio "String Reverse" correctamente. 
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/fa5f813a-dc77-43ab-9bbc-1619bfa24637)

**Comment by Arizat** [comment]
Se realiza el ejercicio "Java Loops" correctamente.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/4f0881cf-56fb-426b-840e-58949ffbd8c2)

**Comment by Arizat** [comment]
Se realiza el ejercicio "Int to String" correctamente.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/6e682cef-bc59-4a99-88be-5e1a3abdbf32)

**Comment by Arizat** [comment]
Se realiza el ejercicio "Instance Of" correctamente.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/22be5784-5e2c-41d7-bce9-836e8157a2c9)

**Comment by Arizat** [comment]
Se realiza correctamente el ejercicio "Inherence".
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/69457972-9eff-4730-b66c-00415645f39a)

**Comment by Arizat** [comment]
Se realizo correctamente el ejercicio "Method Overriding". 
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/3d3b7874-349e-4a75-9a7f-6106e78f90cf)

**Comment by Arizat** [comment]
Se realizó correctamente el ejercicio "Birthday Cake".
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/12543cdb-0544-4554-ad90-dd2bc580b598)

**Comment by Arizat** [comment]
se realiza correctamente el ejercicio "Pairs".
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/a3c524cc-9a8d-4820-a8c4-498067f0b44b)

**Comment by Arizat** [comment]
Se desarrollo el curso de Java Correctamente.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/a1d11918-0c2b-4313-a34a-23e984cdcc8f)

**Comment by Arizat** [comment]
Se realiza el curso de SQL 
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/925c3387-f86d-40bd-8f1e-3582d9184c9b)

**Comment by Arizat** [comment]
Se realizó el correctamente el curso de GitHub.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/2ea9e12a-89a3-485d-b5f3-2ec9d3790a3e)

**Comment by Arizat** [comment]
Se realiza el ejercicio "Select all".
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/0449c598-1820-4fe0-baed-3d1b3af5d104)

**Comment by Arizat** [comment]
Se realizo el ejercicio japanese cities.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/ba8ca3f0-058b-4886-8351-eeae4d105fea)

**Comment by Arizat** [comment]
Ejercicio microservicio Springboot parte 1,2,3 desarrollado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/79408c02-a037-4693-acc7-cad223b0bf85)

**Comment by Arizat** [comment]
Certificado de scrum adquirido.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/14fa5702-8b10-437f-b03c-92751d8053ff)

**Comment by Arizat** [comment]
Ejercicio If Else realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/ee190fc3-dabc-442f-96f5-023ffbcb2234)

**Comment by Arizat** [comment]
Ejercicio the report realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/c377291d-e30e-4688-8d1f-75067d9f645f)

**Comment by Arizat** [comment]
Ejercicio New Companies realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/36a3558e-473e-48b5-9c2e-1ed95b163f6e)

**Comment by Arizat** [comment]
Ejercicio Weater Observation Station realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/ff846c95-8ae9-4c61-be9e-05155a59d7c1)

**Comment by Arizat** [comment]
Curso de Github y Java Spring API Rest realizados
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/5943cd40-676f-4e64-8432-6774a9b223de)

**Comment by Arizat** [comment]
Ejercicio Highest value palindrome.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/48aab9c1-9675-4515-9ec9-e23f5b6a001b)

**Comment by Arizat** [comment]
Ejercicio Recursion: Fibonacci Numbers Realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/131737056/c97d4eee-191c-4c48-ae33-26cea7819aa8)

**Comment by Arizat** [comment]
Se marcan como realizados los ejercicios y se añade evidencia.
Aún en la sección 12 de Docker (No pudo avanzar por tema de los oídos).
