### ISSUE TITLE
Ruta Mateo

### ISSUE THREAD

**Issue by JidokaCommunity** [JidokaCommunity/trainning#8]
**Plan de formación**
- [x] [ Curso Lógica de Programación ](https://www.udemy.com/course/aprende-logica-de-programacion/learn/lecture/27553458?start=0#overview)
- [x] [Curso Lógica de Programación Avanzada](https://www.udemy.com/course/aprende-logica-de-programacion-avanzado/learn/lecture/29294378?start=0#overview)     
- [x] [Curso Java Profesional desde cero](https://drive.google.com/drive/folders/1GWbZ6AS2D4tJCPkNerxlA31VpSo0b33E?usp=sharing)       
- [x] [ Curso API- Rest](https://drive.google.com/drive/folders/137RzGjBm1VeUkMPXpIpA3K1ZMnt6EvJY)      
- [x] [ Git - Githup]( https://platzi.com/cursos/git-github/)     
- [ ] [Curso de Docker](https://drive.google.com/drive/folders/1irQ22NuKdO3xiJeO3THIdkqrYxlKV0D0)       
- [x] [Curso SQL]( https://www.udemy.com/course/aprende-sql-desde-cero-hasta-avanzado-como-un-profesional/)

      
**Retos Java Hackerank**

- [x] [Sustring]( https://www.hackerrank.com/challenges/java-substring/problem?isFullScreen=true)
- [x] [String Reverse](https://www.hackerrank.com/challenges/java-string-reverse/problem?isFullScreen=true)
- [x] [If-else](https://www.hackerrank.com/challenges/java-if-else/problem?isFullScreen=true)
- [x] [Loops](https://www.hackerrank.com/challenges/java-loops-i/problem?isFullScreen=true)
- [x] [Into String](https://www.hackerrank.com/challenges/java-int-to-string/problem?isFullScreen=true)
- [x] [Intanceof](https://www.hackerrank.com/challenges/java-instanceof-keyword/problem?isFullScreen=true)
- [x] [InHeritance](https://www.hackerrank.com/challenges/java-inheritance-1)
- [x] [Method Overriding](https://www.hackerrank.com/challenges/java-method-overriding)
- [x] [Birhday Cake Candels](https://www.hackerrank.com/challenges/birthday-cake-candles/problem?isFullScreen=true)
- [x] [Value Palindrome](https://www.hackerrank.com/challenges/richie-rich/problem?isFullScreen=true)
- [x] [Pairs](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [x] [Fibonacci](https://www.hackerrank.com/challenges/pairs/problem?isFullScreen=true)
- [x] [Fibonacci Numbers](https://www.hackerrank.com/challenges/ctci-fibonacci-numbers/problem?h_r=internal-search)

**Retos SQL**

- [x] [Select all](https://www.hackerrank.com/challenges/select-all-sql/problem?isFullScreen=true)
- [x] [Japanese Cities'Name](https://www.hackerrank.com/challenges/japanese-cities-name/problem?isFullScreen=true)
- [x] [New Companies](https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true)
- [x] [Weather Observation station 20](https://www.hackerrank.com/challenges/weather-observation-station-20/problem?isFullScreen=true)
- [x] [The report](https://www.hackerrank.com/challenges/the-report/problem?isFullScreen=true)

**Taller de Springboot**-  taller para construir microservicios desde cero, estos tres enlaces son una guía para construir microservicios en Springboot, se deben leer y desarrollar en el mismo orden que se citan a continuación:

- [x] [Parte 1](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-1/)
- [x] [Parte 2](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-2/)
- [x] [Parte 3](https://sinbugs.com/como-crear-un-microservicio-o-servicio-web-rest-con-spring-boot-parte-3/)

**Certificación Scrum Foundation** 

- [x] Certificado Scrum

**Comment by JidokaCommunity** [comment]
Empezando el modulo 11 de docker

**Comment by martinezmateo** [comment]
Ejercicio Substring realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/4dcaa54f-5b2f-4612-8dc0-6a2202fb9a86)

**Comment by martinezmateo** [comment]
String reverse realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/ebdb2845-3e60-4f64-a6da-0cb1415734a2)

**Comment by martinezmateo** [comment]
curso de java completado
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/2c4f4e97-3719-4c23-a82d-2c012bd03e1c)

**Comment by martinezmateo** [comment]
curso SQL completado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/aced6315-2251-421a-ab7d-b42814069c72)

**Comment by martinezmateo** [comment]
Certificado de scrum realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/3bca6466-1332-4a5a-a845-7f71e741b011)

**Comment by martinezmateo** [comment]
Taller de Springboot tres partes realizado correctamente

**Comment by martinezmateo** [comment]
Ejercicio If Else realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/feaffa6b-8326-48ee-ae92-c03c6333f13b)

**Comment by martinezmateo** [comment]
Ejercicio Java Loops realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/8da89e0e-f418-4fec-8425-1b6cd9137f6d)

**Comment by martinezmateo** [comment]
Java Instanceof Keyword realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/f1b9c8cd-1e45-4a3e-811e-abd8ed9df338)

**Comment by martinezmateo** [comment]
Curso de Github y API Rest Java Srping realizados.
![Sin título](https://github.com/JidokaCommunity/trainning/assets/68927762/ea1b90f7-bb2c-4769-923a-6a96cb6ac69c)

**Comment by martinezmateo** [comment]
Ejercicio de Java Inherence realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/b2674130-c3c4-48d2-8002-4ed959c730f6)

**Comment by martinezmateo** [comment]
Ejercicio de Method Overriding realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/22619337-c8c1-47b2-a3ca-1804893fda76)

**Comment by martinezmateo** [comment]
Ejercicio Birthday Cake candles
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/252a30b3-5922-41c2-8aae-756c9d1f3ff4)

**Comment by martinezmateo** [comment]
ejercicio Highest value palindrome
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/ef36c4c4-f1a9-44f6-bbd1-1c05915f352d)

**Comment by martinezmateo** [comment]
Ejercicio Pairs realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/6834d8bc-9676-4b73-a675-f468ec6c787d)

**Comment by martinezmateo** [comment]
Ejercicio Fibonacci Numbers realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/1a3a0f05-3daf-482e-bcfa-13aeec663369)

**Comment by martinezmateo** [comment]
Ejercicio Int to String realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/a99e89f9-5ee2-495c-8f5a-54a0fee9dcc3)

**Comment by martinezmateo** [comment]
Ejercicio Select All realizado
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/29fbae7e-281d-495f-9959-d4b8d502d332)

**Comment by martinezmateo** [comment]
Ejercicio Japanese Cities Names realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/135bf094-2ce7-48fb-8676-072c25e2b9d8)

**Comment by martinezmateo** [comment]
Ejercicio New Companies realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/5bf1ac10-5048-4841-9677-c6fe93656ffa)

**Comment by martinezmateo** [comment]
Ejercicio Wheather Observation Station realziado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/baf44d1d-a5f1-4b2c-9206-cd69b90a06a3)

**Comment by martinezmateo** [comment]
Ejercicio the report realizado.
![imagen](https://github.com/JidokaCommunity/trainning/assets/68927762/58e83c47-383a-471c-b212-b22d2febf450)

**Comment by martinezmateo** [comment]
Finalizando el módulo 13 de Docker.
Se marca como realizados los ejercicios y se añade evidencia.

**Comment by JidokaCommunity** [comment]
@martinezmateo termino de ver el video 117 de docker y esta terminando despliegue de un ejercicios en aws

**Comment by JidokaCommunity** [comment]
Terminó docker
